# Global icon map (built once at import)
$Global:DrLogIcons = @{
    # ==== Base mappings (as provided) ====
    'action'                = '🛠️'
    'alert'                 = '❗'
    'alertactive'           = '🚨'
    'alertcleared'          = '✅'
    'alertmuted'            = '🔕'
    'api'                   = '🔗'
    'attach'                = '📎'
    'backup'                = '💾'
    'baseline'              = '📋'
    'battery'               = '🔋'
    'blocked'               = '🚫'
    'brain'                 = '🧠'
    'bugcheck'              = '🧩'
    'canceled'              = '❌'
    'chemistry'             = '🧪'
    'cleanup'               = '🧹'
    'clock1'                = '🕒'
    'clock'                 = '🕓'
    'compare'               = '🔍'
    'completed'             = '✔️'
    'computer'              = '🖥'
    'critical'              = '🚨'
    'database'              = '🗃️'
    'debug'                 = '🐞'
    'deleted'               = '🗑️'
    'dependency'            = '🪝'
    'detail'                = '📝'
    'details'               = '📝'
    'disk'                  = '💽'
    'disk-details'          = '🖴'
    'download'              = '⬇️'
    'drmodule'              = '🧱'
    'endoflist'             = '🔚'
    'endsection'            = '📦'
    'environment'           = '🌐'
    'error'                 = '❌'
    'event'                 = '📅'
    'eye'                   = '👁️'
    'failed'                = '❌'
    'file'                  = '📄'
    'fileaction'            = '📄🛠️'
    'filehandling'          = '📄🔄'
    'folder'                = '📂'
    'folderclosed'          = '📁🔒'
    'hardware'              = '🛠️'
    'id'                    = '🆔'
    'id2'                   = '🪪'
    'inprogress'            = '🔄'
    'info'                  = 'ℹ️'
    'install'               = '📦'
    'jobcheck'              = '✔️'
    'jobend'                = '🎯'
    'jobendarrow'           = '🔚'
    'jobfinalized'          = '📦'
    'joblifecycle'          = '🔁'
    'jobprogress'           = '🔄'
    'jobstart'              = '🚀'
    'jobtools'              = '🛠️'
    'key'                   = '🔑'
    'license'               = '🧾'
    'list'                  = '📋'
    'lock'                  = '🔒'
    'lockandkey'            = '🔐'
    'logfile'               = '📄'
    'magnet'                = '🧲'
    'mailbox'               = '📭'
    'module'                = '🧱'
    'monitor'               = '📈'
    'network'               = '🌐'
    'no'                    = '🚫'
    'nopermissions'         = '🚫'
    'nopermissionsalt'      = '⛔'
    'note'                  = '📝'
    'number'                = '#'
    'numbers'               = '🔢'
    'numberpad'             = '🔢'
    'numpad'                = '🔢'
    'ok'                    = '✔️'
    'openfolder'            = '📂'
    'optical'               = '📀'
    'permission'            = '🔐'
    'power'                 = '⚡'
    'powercheck'            = '📶'
    'printer'               = '🖨️'
    'process'               = '⚙️'
    'properties'            = '📋'
    'property'              = '📋'
    'received'              = '📥'
    'recordupdate'          = '✏️'
    'recovery'              = '🛟'
    'refresh'               = '🔄'
    'rejected'              = '📛'
    'registry'              = '🧬'
    'repair'                = '🛠️'
    'resolvealert'          = '🧹'
    'restart'               = '🔁'
    'restore'               = '♻️'
    'scan'                  = '🔍'
    'schedule'              = '📆'
    'script'                = '📜'
    'search'                = '🔍'
    'security'              = '🛡️'
    'sendalert'             = '📣'
    'inbox'                 = '📤'
    'send'                  = '📨'
    'sent'                  = '📨'
    'service'               = '🧩'
    'settings'              = '⚙️'
    'settingsoverride'      = '⚙️'
    'shutdown'              = '📴'
    'skipped'               = '⏭️'
    'startup'               = '🚀'
    'status'                = '📶'
    'statusfail'            = '🔴'
    'statusok'              = '🟢'
    'statuswarn'            = '🟡'
    'storage'               = '🗄️'
    'success'               = '✅'
    'syncroapi'             = '🔗'
    'system'                = '🖥️'
    'systemaction'          = '🛠️'
    'systemdecision'        = '🧭'
    'systeminfo'            = '📶'
    'systeminit'            = '🧰'
    'systemlogic'           = '🧮'
    'systemmessage'         = '📶'
    'systemtools'           = '🪛'
    'systemupdate'          = '🔧'
    'summary'               = '📋'
    'task'                  = '📌'
    'terminate'             = '💀'
    'terminated'            = '💀'
    'ticket'                = '🎫'
    'ticketclosed'          = '📫'
    'ticketcomment'         = '💬'
    'ticketcreated'         = '🎫'
    'tickethandling'        = '📋'
    'ticketinfo'            = '💳'
    'ticketupdate'          = '🛠️'
    'timeout'               = '⏱️'
    'timer'                 = '⏱️'
    'trophy'                = '🏆'
    'uninstall'             = '🗑️'
    'unlocked'              = '🔓'
    'update'                = '🔄'
    'upload'                = '⬆️'
    'ups'                   = '🔌'
    'user'                  = '👤'
    'voltage'               = '🔌'
    'warning'               = '⚠️'
    'watch'                 = '👁️'
    'wrench'                = '🔧'

    # ==== CPU-related mappings ====
    'cpu'                   = '🖥️'
    'cpuprocess'            = '🧠'
    'cpuhardware'           = '⚙️'
    'cpublock'              = '🔲'
    'cputrack'              = '🖲️'
    'cpunetwork'            = '🖧'
    'cpucompute'            = '🖩'
    'cputemp'               = '🖥️🌡️'

    # ==== Sensors / temps ====
    'thermometer'           = '🌡️'
    'heat'                  = '🔥'
    'cooling'               = '❄️'

    # ==== Totals / counts ====
    'total'                 = 'Σ'
    'totals'                = 'Σ'
    'sum'                   = '∑'
    'count'                 = '#'
    'counts'                = '#'
    'tally'                 = 'Σ'

    # ==== Core warning severities ====
    'warninglow'            = '🔶'
    'warningsevere'         = '‼️'
    'warningcritical'       = '🚨'

    # ==== Diamond severity family ====
    'warninglow-diamond'    = '🔶'
    'warning-diamond'       = '🔷'
    'warningsevere-diamond' = '♦️'

    # ==== Color-circle options ====
    'circle-orange'         = '🟠'
    'circle-yellow'         = '🟡'
    'circle-green'          = '🟢'
    'circle-blue'           = '🔵'
    'circle-purple'         = '🟣'
    'circle-brown'          = '🟤'
    'circle-white'          = '⚪'
    'circle-red'            = '🔴'

    # ==== Bright squares ====
    'square-red'            = '🟥'
    'square-orange'         = '🟧'
    'square-yellow'         = '🟨'
    'square-green'          = '🟩'
    'square-blue'           = '🟦'
    'square-purple'         = '🟪'
    'square-brown'          = '🟫'
    'square-white'          = '⬜'

    # ==== Diamonds (generic options) ====
    'diamond-orange-large'  = '🔶'
    'diamond-blue-large'    = '🔷'
    'diamond-orange-small'  = '🔸'
    'diamond-blue-small'    = '🔹'

    # ==== Triangle alternatives ====
    'triangle-up-red'       = '🔺'
    'triangle-down-red'     = '🔻'
    'triangle-up-white'     = '🔼'
    'triangle-down-white'   = '🔽'

    # ==== Memory / usage / components ====
    'memory'                = '🎛️'
    'usage'                 = '📊'
    'ecchip'                = '📟'
    'component'             = '📟'

    # ==== Charts ====
    'pie'                   = '◔'
    'piehalf'               = '◑'
    'piefull'               = '◕'
    'chart'                 = '◔'

    # ==== Recycling / sustainability ====
    'recycle'               = '♻️'
    'recycling'             = '♻️'
    'recyclebin'            = '♻️'
    'reuse'                 = '🔄'
    'cycle'                 = '🔄'
    'circulararrows'        = '🔄'
    'circular-arrows'       = '🔄'
    'sustainability'        = '🌱'
    'eco'                   = '🌱'
    'green'                 = '🌱'
}

function Get-LogIcon {
    param ([string]$Icon)

    if ([string]::IsNullOrWhiteSpace($Icon)) { return '❓' }

    $key = $Icon.ToLowerInvariant()

    if ($Global:DrLogIcons -and $Global:DrLogIcons.ContainsKey($key)) {
        return $Global:DrLogIcons[$key]
    }

    return '❓'
}
